import pandas as pd
import numpy as np

def compute_rsi(series: pd.Series, window: int = 14) -> pd.Series:
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=window, min_periods=window).mean()
    avg_loss = loss.rolling(window=window, min_periods=window).mean()
    rs = avg_gain / (avg_loss + 1e-9)
    return 100 - (100 / (1 + rs))


def compute_macd(series: pd.Series, fast: int = 12, slow: int = 26, signal: int = 9):
    ema_fast = series.ewm(span=fast, adjust=False).mean()
    ema_slow = series.ewm(span=slow, adjust=False).mean()
    macd_line = ema_fast - ema_slow
    signal_line = macd_line.ewm(span=signal, adjust=False).mean()
    macd_hist = macd_line - signal_line
    return macd_line, signal_line, macd_hist


def compute_atr(df: pd.DataFrame, window: int = 14) -> pd.Series:
    high_low = df['High'] - df['Low']
    high_close = (df['High'] - df['price'].shift(1)).abs()
    low_close = (df['price'] - df['Low'].shift(1)).abs()
    true_range = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
    return true_range.rolling(window=window).mean()


def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Adds multivariate technical features and volatility signals."""
    print("Engineering features...")
    df = df.copy()

    # Technical indicators
    df['rsi_14'] = compute_rsi(df['price'], window=14)
    df['macd_line'], df['macd_signal'], df['macd_hist'] = compute_macd(df['price'])
    df['atr_14'] = compute_atr(df)
    df['obv'] = (np.sign(df['price'].diff().fillna(0)) * df['Volume']).cumsum()

    # Price momentum and moving averages
    df['ema_7'] = df['price'].ewm(span=7, adjust=False).mean()
    df['ema_14'] = df['price'].ewm(span=14, adjust=False).mean()
    df['price_mom_7'] = df['price'] - df['price'].shift(7)
    df['price_mom_14'] = df['price'] - df['price'].shift(14)

    # Volume-based features
    df['volume_roc_7'] = df['Volume'].pct_change(7)
    df['volume_roc_14'] = df['Volume'].pct_change(14)

    # Lag features for the target price
    for lag in [1, 2, 3, 7, 14, 30]:
        df[f'price_lag_{lag}'] = df['price'].shift(lag)

    # Rolling statistics on price and returns
    for window in [7, 14, 30]:
        df[f'rolling_mean_{window}'] = df['price'].rolling(window=window).mean()
        df[f'rolling_std_{window}'] = df['price'].rolling(window=window).std()
        df[f'rolling_min_{window}'] = df['price'].rolling(window=window).min()
        df[f'rolling_max_{window}'] = df['price'].rolling(window=window).max()
        df[f'returns_std_{window}'] = df['returns'].rolling(window=window).std()

    # Rolling volatility signals
    df['volatility_7'] = df['returns'].rolling(window=7).std()
    df['volatility_30'] = df['returns'].rolling(window=30).std()
    df['realized_vol_21'] = df['returns'].rolling(window=21).std() * np.sqrt(252)
    df['realized_vol_63'] = df['returns'].rolling(window=63).std() * np.sqrt(252)

    # Drop NaNs generated by indicator calculations
    df.dropna(inplace=True)
    print(f"Features engineered. Dataset shape: {df.shape}")
    return df

def make_stationary(series: pd.Series, d: int = 1) -> pd.Series:
    """Applies differencing to make series stationary."""
    for _ in range(d):
        series = series.diff().dropna()
    return series
